### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by Exekutori** [fosslife/grambot#4]
how to run on heroku?
please add the button on the README.md

**Comment by Gamaxi** [comment]
I also have the same problem...

**Comment by Sparkenstein** [comment]
Sorry for the delay

as per the request, the button has been added. I don't know much of heroku, so for now after deployment, you have to click the following toggle on heroku to start the bot, other than that the button is working fine.

![image](https://user-images.githubusercontent.com/24642451/145837107-a5abdcbd-513b-485f-aae8-4bd6f875a26c.png)


if someone knows how to make it work feel free to PR
